server:
  port: 8999

spring:
  application:
    name: breathe-minio
  #解决swagger版本兼容报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      server-addr: 192.168.10.150:8848
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB

minio:
  endpoint: http://192.168.10.150:9000
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  secure: false
  bucket-name: commons # 桶名 我这是给出了一个默认桶名
  image-size: 10485760 # 我在这里设定了 图片文件的最大大小
  file-size: 1073741824 # 此处是设定了文件的最大大小

