server:
  port: 8003

spring:
  application:
    name: breathe-posts
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.150:3306/breathe?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  #解决swagger版本兼容报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      server-addr: 192.168.10.150:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
  redis:
    host: 192.168.10.150
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 30000

mybatis-plus:
  mapper-locations: classpath:cn/alectang/posts/mapper/xml/*.xml